# Who the signed-in person is to the agents. The controllers generated by
# managed_agents use this for everything they look up, so nobody reaches a
# session or a credential that isn't theirs.
module AgentAccess
  extend ActiveSupport::Concern

  private

  # Sessions belong to this record. Return the signed-in user, or their
  # account to share sessions across an organisation.
  def agent_owner
    current_user
  end

  def agent_sessions
    ManagedAgents::Session.owned_by(agent_owner)
  end

  # The groups of credentials this person may manage, by label. "personal"
  # connections are used only by their own sessions. To keep shared service
  # accounts in the hands of admins, leave "organization" out for others.
  def agent_vault_owners
    {"personal" => agent_owner, "organization" => current_user&.account}.compact
  end
end
