Rails.application.routes.draw do
  root "tickets#index"

  resources :tickets, only: [:index, :show, :new, :create, :update] do
    resource :triage, only: :create, module: :tickets
  end
  resource :digest, only: :create

  # Generated by `bin/rails generate managed_agents:chat`: every session, with full transcripts.
  resources :agent_sessions, only: [:index, :show, :create] do
    scope module: :agent_sessions do
      resources :messages, only: :create
      resources :confirmations, only: :create
      resource :interrupt, only: :create
    end
  end

  mount ManagedAgents::Engine => "/managed_agents"

  get "up" => "rails/health#show", :as => :rails_health_check
end
