Rails.application.routes.draw do
  root "boards#index"

  resources :boards, only: [:index, :show, :create] do
    resources :messages, only: :create, module: :boards
  end
  resources :lists, only: [] do
    resources :cards, only: :create
  end
  resources :cards, only: [:update, :destroy]

  # Generated by `bin/rails generate managed_agents:chat`: every session, with full transcripts.
  resources :agent_sessions, only: [:index, :show, :create] do
    scope module: :agent_sessions do
      resources :messages, only: :create
      resources :confirmations, only: :create
      resource :interrupt, only: :create
    end
  end

  mount ManagedAgents::Engine => "/managed_agents"

  get "up" => "rails/health#show", :as => :rails_health_check
end
